import subprocess
import sys
from pathlib import Path

import module.auto_rig as auto_rig

ROOT = Path(__file__).resolve().parent.parent

EXPECTED_PUBLIC_API = {
    "AUTO_RIG_INPUT_CONTRACT_VERSION",
    "ArtifactContractError",
    "AutoRigCanvasContract",
    "AutoRigContractError",
    "AutoRigInputContract",
    "AutoRigPartContract",
    "AutoRigTagContractError",
    "BASE_FEATURE_SCALE_KIND",
    "BUILTIN_NATIVE_VARIANT_ROLE_ENVELOPES",
    "CANONICAL_PNG_ENCODER_VERSION",
    "CANONICAL_TEXTURE_PAGE_SET_VERSION",
    "CanonicalPartTag",
    "CanonicalLabelMap",
    "CanonicalPngEncoderDescriptor",
    "CanonicalTexturePageSet",
    "DRAW_ANCHOR_EXPANDER_VERSION",
    "DRAW_ORDER_POLICY_VERSION",
    "DrawOrderPolicyError",
    "ERROR_RECORD_PATH",
    "EXPORT_MANIFEST_PATH",
    "FileDigest",
    "FormatValidation",
    "FINAL_DRAW_ORDER_PLAN_VERSION",
    "FinalDrawOrderPlan",
    "FinalPartDrawRecord",
    "IntrusionPartMetric",
    "LoadedPartAlpha",
    "LoadedTextureRegion",
    "LIVE2D_PROJECTED_DRAWABLE_LIMIT",
    "MASK_COMPONENT_ID_SCHEMA",
    "MASK_COMPONENT_PLAN_VERSION",
    "NATIVE_VARIANT_COMPOSITE_MODE",
    "NATIVE_VARIANT_COMPOSITE_PLAN_VERSION",
    "NATIVE_VARIANT_ADMISSION_POLICY_VERSION",
    "NATIVE_VARIANT_ADMISSION_PRIORITY",
    "NATIVE_VARIANT_ELIGIBILITY_PLAN_VERSION",
    "NATIVE_VARIANT_MANIFEST_VERSION",
    "NATIVE_VARIANT_PARTITION_VERSION",
    "NATIVE_VARIANT_QUALITY_PLAN_VERSION",
    "NATIVE_VARIANT_ROLE_ENVELOPE_VERSION",
    "NATIVE_VARIANT_ROLES",
    "NATIVE_VARIANT_SET_VERSION",
    "MaskCleanupDescriptor",
    "MaskComponentPlan",
    "MaskComponentPlanError",
    "MaskComponentRecord",
    "NormalizedMaskPart",
    "NativeVariantCandidate",
    "NativeVariantAdmissionAttempt",
    "NativeVariantAdmissionError",
    "NativeVariantBranchMetrics",
    "NativeVariantBundleQualityResult",
    "NativeVariantContractError",
    "NativeVariantPartitionRecord",
    "NativeVariantQualityError",
    "NativeVariantQualityPlan",
    "NativeVariantQualityResult",
    "NativeVariantRoleEnvelope",
    "NativeVariantSet",
    "NativeVariantEligibilityPlan",
    "OrdinaryDrawOrderPlan",
    "PartDrawOrderRecord",
    "MaterializedTexturePage",
    "QCL_CODEC_VERSION",
    "QclContractError",
    "StageFailureRecord",
    "StageGraphContractError",
    "StageGraphResult",
    "StageGraphValidator",
    "StageManifest",
    "StageManifestError",
    "StageNode",
    "StageValidationIssue",
    "STAGE_MANIFEST_SCHEMA_VERSION",
    "SUPPORTED_CANVAS_EDGES",
    "TEXTURE_EXTRUSION_PX",
    "TEXTURE_MAX_PAGES",
    "TEXTURE_PACKER_VERSION",
    "TEXTURE_PAGE_PLAN_VERSION",
    "TEXTURE_PAGE_SIZE",
    "TEXTURE_PIXEL_CONTRACT_VERSION",
    "TEXTURE_RECTANGLE_BUILDER_VERSION",
    "TEXTURE_SAFETY_GAP_PX",
    "TerminalFinalizationError",
    "TerminalFinalizationResult",
    "TERMINAL_FINALIZER_VERSION",
    "TEXTURE_RUNTIME_CONTRACT_VERSION",
    "TextureRuntimeContract",
    "ValidatedPartSource",
    "VALID_PRODUCTION_STAGE_STATUSES",
    "VALID_TERMINAL_STAGE_STATUSES",
    "TexturePagePlan",
    "TexturePageRecord",
    "TexturePlanError",
    "TextureRect",
    "TextureRegionInput",
    "TextureRegionPlacement",
    "admit_native_variant_resources",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_stage_fingerprint",
    "build_stage_manifest",
    "build_base_mask_component_plan",
    "build_native_variant_quality_plan",
    "build_ordinary_draw_order",
    "build_texture_page_plan",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "describe_file",
    "decode_qcl",
    "encode_qcl",
    "extend_mask_component_plan_with_variants",
    "expand_draw_order_with_admitted_variants",
    "finalize_failure",
    "finalize_success",
    "invalidate_terminal",
    "is_item_completed",
    "load_auto_rig_input_contract",
    "load_native_variant_set",
    "load_base_texture_regions",
    "load_native_texture_regions",
    "load_validated_part_alphas",
    "manifest_relative_path",
    "normalize_relative_path",
    "materialize_canonical_texture_pages",
    "read_stage_manifest",
    "sha256_file",
    "texture_region_input",
    "validate_draw_order_registry",
    "validate_native_variant_role_registry",
    "validate_v3_final_tag_set",
    "write_stage_manifest",
}


def test_auto_rig_exports_only_the_supported_foundation_api() -> None:
    assert set(auto_rig.__all__) == EXPECTED_PUBLIC_API
    assert all(hasattr(auto_rig, name) for name in EXPECTED_PUBLIC_API)


def test_auto_rig_import_has_no_heavy_runtime_dependencies() -> None:
    script = """
import sys
import module.auto_rig
heavy = sorted(
    name
    for name in ('torch', 'cv2', 'psd_tools', 'numpy', 'scipy', 'skimage')
    if name in sys.modules
)
print(','.join(heavy))
"""

    completed = subprocess.run(
        [sys.executable, "-c", script],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    assert completed.stdout.strip() == ""
