"""Deterministic contracts for the see-through auto-rig pipeline."""

from .artifacts import (
    ArtifactContractError,
    FileDigest,
    atomic_write_bytes,
    atomic_write_json,
    canonical_json_bytes,
    canonical_json_sha256,
    describe_file,
    normalize_relative_path,
    sha256_file,
)
from .contracts import (
    AUTO_RIG_INPUT_CONTRACT_VERSION,
    SUPPORTED_CANVAS_EDGES,
    AutoRigCanvasContract,
    AutoRigContractError,
    AutoRigInputContract,
    AutoRigPartContract,
    ValidatedPartSource,
    load_auto_rig_input_contract,
)
from .manifests import (
    StageManifest,
    StageManifestError,
    build_stage_fingerprint,
    build_stage_manifest,
    manifest_relative_path,
    read_stage_manifest,
    write_stage_manifest,
)
from .stage_graph import (
    StageGraphContractError,
    StageGraphResult,
    StageGraphValidator,
    StageNode,
    StageValidationIssue,
)
from .tag_registry import (
    AutoRigTagContractError,
    CanonicalPartTag,
    validate_v3_final_tag_set,
)
from .terminal import (
    ERROR_RECORD_PATH,
    EXPORT_MANIFEST_PATH,
    FormatValidation,
    StageFailureRecord,
    TerminalFinalizationError,
    TerminalFinalizationResult,
    finalize_failure,
    finalize_success,
    invalidate_terminal,
    is_item_completed,
)

__all__ = [
    "AUTO_RIG_INPUT_CONTRACT_VERSION",
    "ArtifactContractError",
    "AutoRigCanvasContract",
    "AutoRigContractError",
    "AutoRigInputContract",
    "AutoRigPartContract",
    "AutoRigTagContractError",
    "CanonicalPartTag",
    "ERROR_RECORD_PATH",
    "EXPORT_MANIFEST_PATH",
    "FileDigest",
    "FormatValidation",
    "StageFailureRecord",
    "StageGraphContractError",
    "StageGraphResult",
    "StageGraphValidator",
    "StageManifest",
    "StageManifestError",
    "StageNode",
    "StageValidationIssue",
    "SUPPORTED_CANVAS_EDGES",
    "TerminalFinalizationError",
    "TerminalFinalizationResult",
    "ValidatedPartSource",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_stage_fingerprint",
    "build_stage_manifest",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "describe_file",
    "finalize_failure",
    "finalize_success",
    "invalidate_terminal",
    "is_item_completed",
    "load_auto_rig_input_contract",
    "manifest_relative_path",
    "normalize_relative_path",
    "read_stage_manifest",
    "sha256_file",
    "validate_v3_final_tag_set",
    "write_stage_manifest",
]
