"""Deterministic contracts for the see-through auto-rig pipeline."""

from .artifacts import (
    ArtifactContractError,
    FileDigest,
    atomic_write_bytes,
    atomic_write_json,
    canonical_json_bytes,
    canonical_json_sha256,
    describe_file,
    normalize_relative_path,
    sha256_file,
)
from .component_plan import (
    MASK_COMPONENT_ID_SCHEMA,
    MASK_COMPONENT_PLAN_VERSION,
    MaskCleanupDescriptor,
    MaskComponentPlan,
    MaskComponentPlanError,
    MaskComponentRecord,
    NormalizedMaskPart,
    build_base_mask_component_plan,
)
from .contracts import (
    AUTO_RIG_INPUT_CONTRACT_VERSION,
    SUPPORTED_CANVAS_EDGES,
    AutoRigCanvasContract,
    AutoRigContractError,
    AutoRigInputContract,
    AutoRigPartContract,
    ValidatedPartSource,
    load_auto_rig_input_contract,
)
from .draw_order import (
    DRAW_ORDER_POLICY_VERSION,
    DrawOrderPolicyError,
    OrdinaryDrawOrderPlan,
    PartDrawOrderRecord,
    build_ordinary_draw_order,
    validate_draw_order_registry,
)
from .manifests import (
    StageManifest,
    StageManifestError,
    build_stage_fingerprint,
    build_stage_manifest,
    manifest_relative_path,
    read_stage_manifest,
    write_stage_manifest,
)
from .mask_sources import LoadedPartAlpha, load_validated_part_alphas
from .qcl import (
    QCL_CODEC_VERSION,
    CanonicalLabelMap,
    QclContractError,
    decode_qcl,
    encode_qcl,
)
from .stage_graph import (
    StageGraphContractError,
    StageGraphResult,
    StageGraphValidator,
    StageNode,
    StageValidationIssue,
)
from .tag_registry import (
    AutoRigTagContractError,
    CanonicalPartTag,
    validate_v3_final_tag_set,
)
from .terminal import (
    ERROR_RECORD_PATH,
    EXPORT_MANIFEST_PATH,
    FormatValidation,
    StageFailureRecord,
    TerminalFinalizationError,
    TerminalFinalizationResult,
    finalize_failure,
    finalize_success,
    invalidate_terminal,
    is_item_completed,
)

__all__ = [
    "AUTO_RIG_INPUT_CONTRACT_VERSION",
    "ArtifactContractError",
    "AutoRigCanvasContract",
    "AutoRigContractError",
    "AutoRigInputContract",
    "AutoRigPartContract",
    "AutoRigTagContractError",
    "CanonicalLabelMap",
    "CanonicalPartTag",
    "DRAW_ORDER_POLICY_VERSION",
    "DrawOrderPolicyError",
    "ERROR_RECORD_PATH",
    "EXPORT_MANIFEST_PATH",
    "FileDigest",
    "FormatValidation",
    "LoadedPartAlpha",
    "MASK_COMPONENT_ID_SCHEMA",
    "MASK_COMPONENT_PLAN_VERSION",
    "MaskCleanupDescriptor",
    "MaskComponentPlan",
    "MaskComponentPlanError",
    "MaskComponentRecord",
    "NormalizedMaskPart",
    "OrdinaryDrawOrderPlan",
    "PartDrawOrderRecord",
    "QCL_CODEC_VERSION",
    "QclContractError",
    "StageFailureRecord",
    "StageGraphContractError",
    "StageGraphResult",
    "StageGraphValidator",
    "StageManifest",
    "StageManifestError",
    "StageNode",
    "StageValidationIssue",
    "SUPPORTED_CANVAS_EDGES",
    "TerminalFinalizationError",
    "TerminalFinalizationResult",
    "ValidatedPartSource",
    "atomic_write_bytes",
    "atomic_write_json",
    "build_base_mask_component_plan",
    "build_ordinary_draw_order",
    "build_stage_fingerprint",
    "build_stage_manifest",
    "canonical_json_bytes",
    "canonical_json_sha256",
    "decode_qcl",
    "describe_file",
    "encode_qcl",
    "finalize_failure",
    "finalize_success",
    "invalidate_terminal",
    "is_item_completed",
    "load_auto_rig_input_contract",
    "load_validated_part_alphas",
    "manifest_relative_path",
    "normalize_relative_path",
    "read_stage_manifest",
    "sha256_file",
    "validate_draw_order_registry",
    "validate_v3_final_tag_set",
    "write_stage_manifest",
]
