# Dataset schema configuration
[schema]
fields = [
    { name = "uris", type = "string" },
    { name = "mime", type = "string" },
    { name = "width", type = "int32" },
    { name = "height", type = "int32" },
    { name = "depth", type = "int32" },
    { name = "channels", type = "int32" },
    { name = "hash", type = "string" },
    { name = "size", type = "int64" },
    { name = "has_audio", type = "bool" },
    { name = "duration", type = "int32" },
    { name = "num_frames", type = "int32" },
    { name = "frame_rate", type = "float32" },
    { name = "blob", type = "binary" },
    { name = "captions", type = "list<string>" },
]

# Console colors configuration
[colors]
animation = "bold_green"
application = "bright red"
audio = "orange1"
caption = "yellow"
image = "green"
text = "yellow"
unknown = "cyan"
video = "magenta"

[tag_type]
fields = [
    { name = "general", id = 0, color = "orange3" },
    { name = "artist", id = 1, color = "bright_red" },
    { name = "studio", id = 2, color = "red" },
    { name = "franchise", id = 3, color = "dark_magenta" },
    { name = "character", id = 4, color = "magenta" },
    { name = "genre", id = 5, color = "bright_magenta" },
    { name = "medium", id = 8, color = "cornflower_blue" },
    { name = "meta", id = 9, color = "bright_blue" },
    { name = "fashion", id = 10, color = "red3" },
    { name = "anatomy", id = 11, color = "orange4" },
    { name = "pose", id = 12, color = "yellow" },
    { name = "activity", id = 13, color = "bright_yellow" },
    { name = "role", id = 14, color = "cyan" },
    { name = "flora", id = 15, color = "green" },
    { name = "fauna", id = 16, color = "bright_green" },
    { name = "entity", id = 17, color = "grey74" },
    { name = "object", id = 18, color = "dark_green" },
    { name = "substance", id = 19, color = "green4" },
    { name = "setting", id = 20, color = "spring_green4" },
    { name = "language", id = 21, color = "bright_cyan" },
    { name = "automatic", id = 22, color = "cyan" },
]

[wdtagger]
# List of series names to exclude from special parsing in split_name_series.
# These are terms that appear in parentheses but should not be treated as a series name.
series_exclude_list = [
    "female",
    "male",
    "character",
    "atlus character",
    "beast style",
    "dangerous beast",
    "amor caren",
    "berserker install",
    "archer install",
    "saber install",
    "assassin install",
    "lancer install",
    "rider install",
    "caster install",
    "young",
    "swimsuit rider",
    "2021 outfit",
    "herrscher of finality",
    "winter princess",
    "creature",
    "kenjuku",
    "pc-98",
    "mooncancer",
]

[reward_model]
quality = [
    { name = "worst_quality", score = 3, color = "bold red" },
    { name = "bad_quality", score = 5, color = "bold yellow" },
    { name = "normal_quality", score = 8.7, color = "bold blue" },
    { name = "best_quality", score = 10, color = "bold green" },
]
