name: Fetch Sankaku Tags

on:
  schedule:
    # 每周一运行一次
    - cron: '0 0 * * 1'
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Fetch Tags
        run: python utils/fetch_sankaku_tags.py
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/sankaku_tags.json data/debug/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Sankaku tags data"
          git push
